[ERROR] 2020-12-01 16:27:37,780 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 10)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 10 offset 0' at line 5")
[ERROR] 2020-12-01 16:27:37,872 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:27:37.781166-127.0.0.1-2b5
[ERROR] 2020-12-01 16:28:10,932 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 0)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None' at line 5")
[ERROR] 2020-12-01 16:28:11,108 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:28:10.933095-127.0.0.1-ec9
[ERROR] 2020-12-01 16:28:25,995 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 10)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 10 offset 0' at line 5")
[ERROR] 2020-12-01 16:28:26,155 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:28:25.996016-127.0.0.1-a93
[ERROR] 2020-12-01 16:29:12,458 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 10)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 10 offset 1' at line 5")
[ERROR] 2020-12-01 16:29:12,540 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:29:12.459153-127.0.0.1-030
[ERROR] 2020-12-01 16:31:59,565 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 49, in get_article
    as_dict=1)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
TypeError: execute() got an unexpected keyword argument 'as_dict'
[ERROR] 2020-12-01 16:31:59,647 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:31:59.565821-127.0.0.1-daa
[ERROR] 2020-12-01 16:32:40,458 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 10)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 10 offset 10' at line 5")
[ERROR] 2020-12-01 16:32:40,554 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:32:40.458715-127.0.0.1-514
[ERROR] 2020-12-01 16:32:55,269 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 20)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 20 offset 10' at line 5")
[ERROR] 2020-12-01 16:32:55,430 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:32:55.270495-127.0.0.1-b56
[ERROR] 2020-12-01 16:33:28,957 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 20)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 20 offset 10' at line 5")
[ERROR] 2020-12-01 16:33:29,038 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:33:28.957961-127.0.0.1-2dd
[ERROR] 2020-12-01 16:33:33,788 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    limit_page_length=kwargs.get("size") or 20)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 20 offset 10' at line 5")
[ERROR] 2020-12-01 16:33:33,873 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:33:33.788779-127.0.0.1-20c
[ERROR] 2020-12-01 16:34:01,857 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 49, in get_article
    as_dict=True)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
TypeError: execute() got an unexpected keyword argument 'as_dict'
[ERROR] 2020-12-01 16:34:01,930 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:34:01.857395-127.0.0.1-791
[ERROR] 2020-12-01 16:34:22,001 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    page_length=kwargs.get("size") or 20)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 20 offset 10' at line 5")
[ERROR] 2020-12-01 16:34:22,192 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:34:22.001917-127.0.0.1-9b7
[ERROR] 2020-12-01 16:34:23,131 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    page_length=kwargs.get("size") or 20)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 20 offset 10' at line 5")
[ERROR] 2020-12-01 16:34:23,136 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:34:23.131378-127.0.0.1-896
[ERROR] 2020-12-01 16:35:12,350 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_article",
 "search": "test"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 48, in get_article
    page_length=kwargs.get("size") or 20)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 130, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'None\n\t\t\tlimit 20 offset 10' at line 5")
[ERROR] 2020-12-01 16:35:12,355 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 16:35:12.350429-127.0.0.1-5d6
