[ERROR] 2020-11-30 17:32:35,074 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:32:35,283 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:32:35.083607-127.0.0.1-197
[DEBUG] 2020-11-30 17:33:34,050 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:34:34,164 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:35:34,318 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:35:44,619 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:35:44,690 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:35:44.619782-127.0.0.1-28c
[DEBUG] 2020-11-30 17:36:42,712 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:37:42,855 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:38:43,006 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:39:18,785 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:39:18,963 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:39:18.785996-127.0.0.1-24a
[DEBUG] 2020-11-30 17:40:17,599 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:41:17,726 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:42:17,860 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:43:17,977 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:44:18,122 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:45:20,107 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:45:20,263 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:45:20.107637-127.0.0.1-ea0
[DEBUG] 2020-11-30 17:46:19,296 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:47:19,439 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:48:19,631 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:50:31,751 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:51:31,866 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:52:11,015 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:52:11,168 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:52:11.016123-127.0.0.1-133
[DEBUG] 2020-11-30 17:53:10,052 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:54:10,173 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 17:57:21,594 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 17:57:21,727 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 17:57:21.594679-127.0.0.1-09e
[DEBUG] 2020-11-30 17:58:20,701 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 17:59:20,809 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 18:00:21,004 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-11-30 20:50:12,595 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-30 20:50:12,702 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-30 20:50:12.596146-127.0.0.1-6f0
[DEBUG] 2020-11-30 20:51:09,856 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:52:10,038 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:53:10,156 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:54:10,312 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:55:10,438 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:56:10,594 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:57:10,731 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:58:10,862 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 20:59:10,986 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-30 21:00:11,139 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 08:58:43,699 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-12-01 08:58:43,876 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 08:58:43.699613-127.0.0.1-349
[DEBUG] 2020-12-01 08:59:42,760 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:00:42,902 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:01:43,046 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:02:43,205 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:03:43,353 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:04:43,529 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:05:43,676 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:06:43,812 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:07:43,949 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:08:44,123 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:09:44,266 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:10:44,409 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:11:44,558 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:12:44,695 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:13:44,857 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:14:44,998 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:15:45,133 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:16:45,295 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:17:45,446 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:18:45,568 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:19:45,683 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:20:45,823 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:21:45,955 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:22:46,112 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:23:46,263 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:24:46,392 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:25:46,521 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:26:46,664 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:27:46,816 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:28:46,991 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:29:47,114 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:30:47,302 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:31:47,458 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:32:47,690 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:33:47,837 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 09:34:39,187 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: 'library_management'
[ERROR] 2020-12-01 09:34:39,264 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 09:34:39.187538-127.0.0.1-f99
[DEBUG] 2020-12-01 09:34:47,963 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:35:48,090 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:36:48,218 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:37:48,355 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:38:48,501 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:39:48,642 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:40:48,797 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:41:48,946 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:42:49,079 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:43:49,215 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:44:49,357 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:45:49,495 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:46:49,609 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:47:49,758 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:48:49,946 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:49:50,091 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:50:50,203 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:51:50,338 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:52:50,502 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:53:50,672 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:54:50,798 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:55:50,924 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:56:51,080 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:57:51,206 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:58:51,331 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 09:59:51,466 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:00:51,627 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:01:51,743 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:02:51,868 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:03:51,992 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:04:52,130 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:05:52,274 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:06:52,409 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:07:52,539 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:08:52,710 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:09:52,825 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:10:52,952 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:11:53,110 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:12:53,268 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:13:53,392 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:14:53,508 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:15:53,625 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:16:53,794 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:17:53,947 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:18:54,063 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:19:54,188 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:20:54,347 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:21:54,482 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:22:54,608 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:23:54,749 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:24:54,882 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:25:55,002 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:26:55,129 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:27:55,253 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:28:55,385 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:29:55,543 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:30:55,675 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:31:55,844 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:32:56,026 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:33:56,141 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:34:56,284 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:35:56,400 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:36:56,554 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:37:56,696 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 10:38:46,617 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 39, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax
[ERROR] 2020-12-01 10:38:46,830 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:38:46.618350-127.0.0.1-905
[ERROR] 2020-12-01 10:38:48,143 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.desk.doctype.notification_settings.notification_settings.set_seen_value",
 "user": "Administrator",
 "value": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 39, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax
[ERROR] 2020-12-01 10:38:48,181 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:38:48.143667-127.0.0.1-d2f
[ERROR] 2020-12-01 10:39:45,618 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Exception in Enqueue Events for Site library.test
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 84, in enqueue_events_for_site
    enqueue_events(site=site, queued_jobs=queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 111, in enqueue_events
    out = enqueue_applicable_events(site, nowtime, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 129, in enqueue_applicable_events
    trigger_if_enabled(site, event, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 122, in trigger_if_enabled
    trigger(site, event, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 147, in trigger
    events_from_hooks = get_scheduler_events(event)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 179, in get_scheduler_events
    scheduler_events = frappe.get_hooks("scheduler_events")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax

[ERROR] 2020-12-01 10:40:35,021 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 73, in application
    response = frappe.website.render.render()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/render.py", line 36, in render
    resolve_redirect(path)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/redirect.py", line 23, in resolve_redirect
    redirects = frappe.get_hooks('website_redirects')
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax
[ERROR] 2020-12-01 10:40:35,045 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:40:35.021796-127.0.0.1-9a3
[ERROR] 2020-12-01 10:40:45,747 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Exception in Enqueue Events for Site library.test
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 84, in enqueue_events_for_site
    enqueue_events(site=site, queued_jobs=queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 111, in enqueue_events
    out = enqueue_applicable_events(site, nowtime, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 129, in enqueue_applicable_events
    trigger_if_enabled(site, event, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 122, in trigger_if_enabled
    trigger(site, event, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 147, in trigger
    events_from_hooks = get_scheduler_events(event)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 179, in get_scheduler_events
    scheduler_events = frappe.get_hooks("scheduler_events")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax

[ERROR] 2020-12-01 10:40:46,268 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 73, in application
    response = frappe.website.render.render()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/render.py", line 36, in render
    resolve_redirect(path)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/redirect.py", line 23, in resolve_redirect
    redirects = frappe.get_hooks('website_redirects')
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax
[ERROR] 2020-12-01 10:40:46,295 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:40:46.269299-127.0.0.1-295
[ERROR] 2020-12-01 10:40:57,575 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 73, in application
    response = frappe.website.render.render()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/render.py", line 36, in render
    resolve_redirect(path)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/redirect.py", line 23, in resolve_redirect
    redirects = frappe.get_hooks('website_redirects')
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax
[ERROR] 2020-12-01 10:40:57,686 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:40:57.575781-127.0.0.1-1ea
[ERROR] 2020-12-01 10:41:46,152 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 73, in application
    response = frappe.website.render.render()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/render.py", line 36, in render
    resolve_redirect(path)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/redirect.py", line 23, in resolve_redirect
    redirects = frappe.get_hooks('website_redirects')
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax
[ERROR] 2020-12-01 10:41:46,179 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:41:46.152552-127.0.0.1-b42
[ERROR] 2020-12-01 10:41:55,306 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Exception in Enqueue Events for Site library.test
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 84, in enqueue_events_for_site
    enqueue_events(site=site, queued_jobs=queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 111, in enqueue_events
    out = enqueue_applicable_events(site, nowtime, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 129, in enqueue_applicable_events
    trigger_if_enabled(site, event, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 122, in trigger_if_enabled
    trigger(site, event, last, queued_jobs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 147, in trigger
    events_from_hooks = get_scheduler_events(event)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py", line 179, in get_scheduler_events
    scheduler_events = frappe.get_hooks("scheduler_events")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 966, in get_hooks
    hooks = _dict(load_app_hooks())
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 945, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/hooks.py", line 28
    include js in doctype views
             ^
SyntaxError: invalid syntax

[DEBUG] 2020-12-01 10:42:55,457 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 10:43:24,532 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-12-01 10:43:24,723 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:43:24.533237-127.0.0.1-aa9
[ERROR] 2020-12-01 10:43:53,415 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: 'library_management'
[ERROR] 2020-12-01 10:43:53,417 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 10:43:53.415522-127.0.0.1-74b
[DEBUG] 2020-12-01 10:44:23,709 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:45:23,849 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 10:46:23,969 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:05:03,535 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:06:03,658 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:07:03,817 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:08:03,959 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:09:04,123 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:10:04,294 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:11:04,438 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:12:04,581 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:13:04,741 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:14:04,900 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:15:05,050 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:16:05,199 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:17:05,315 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:18:05,430 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:19:05,592 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:20:05,759 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:20:26,373 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "article",
 "pwd": "root",
 "usr": "Administrator"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: 'article'
[ERROR] 2020-12-01 11:20:26,450 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:20:26.373690-127.0.0.1-94a
[ERROR] 2020-12-01 11:20:43,567 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "article"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: 'article'
[ERROR] 2020-12-01 11:20:43,571 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:20:43.568114-127.0.0.1-9e0
[DEBUG] 2020-12-01 11:21:05,899 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:22:06,079 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:23:06,261 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:24:06,449 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:25:06,611 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:26:06,770 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:27:06,931 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:27:18,101 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "article"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: 'article'
[ERROR] 2020-12-01 11:27:18,104 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:27:18.101646-127.0.0.1-3b8
[ERROR] 2020-12-01 11:27:25,325 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "articles"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: 'articles'
[ERROR] 2020-12-01 11:27:25,327 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:27:25.325391-127.0.0.1-d1b
[ERROR] 2020-12-01 11:27:31,582 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": ""
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 216, in get_attr
    method = globals()[cmd]
KeyError: ''
[ERROR] 2020-12-01 11:27:31,584 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:27:31.582873-127.0.0.1-28f
[DEBUG] 2020-12-01 11:28:07,075 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:29:07,177 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:30:07,321 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:31:07,423 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:32:07,583 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:33:07,717 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:34:07,847 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:34:55,953 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "limit_page_length": 20
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 122, in handle
    doctype, **frappe.local.form_dict)})
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 35, in get_list
    limit_start=limit_start, limit_page_length=limit_page_length, ignore_permissions=False)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'article')
[ERROR] 2020-12-01 11:34:55,957 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:34:55.953372-127.0.0.1-82a
[ERROR] 2020-12-01 11:34:59,499 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "limit_page_length": 20
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 122, in handle
    doctype, **frappe.local.form_dict)})
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 35, in get_list
    limit_start=limit_start, limit_page_length=limit_page_length, ignore_permissions=False)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'articles')
[ERROR] 2020-12-01 11:34:59,502 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:34:59.499907-127.0.0.1-028
[DEBUG] 2020-12-01 11:35:07,993 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:36:08,121 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:37:08,237 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:38:08,376 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:39:08,520 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:40:08,710 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:41:08,838 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:42:08,973 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:42:38,366 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "description": "New ToDo"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 125, in handle
    data = get_request_form_data()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 143, in get_request_form_data
    data = json.loads(frappe.safe_decode(frappe.local.request.get_data()))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] 2020-12-01 11:42:38,378 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:42:38.368060-127.0.0.1-f8e
[DEBUG] 2020-12-01 11:43:09,107 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:43:56,621 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "article_name": "New ToDo"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 125, in handle
    data = get_request_form_data()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 143, in get_request_form_data
    data = json.loads(frappe.safe_decode(frappe.local.request.get_data()))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] 2020-12-01 11:43:56,623 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:43:56.621418-127.0.0.1-d1a
[ERROR] 2020-12-01 11:44:06,634 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "article_name": "New ToDo"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 125, in handle
    data = get_request_form_data()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 143, in get_request_form_data
    data = json.loads(frappe.safe_decode(frappe.local.request.get_data()))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] 2020-12-01 11:44:06,638 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:44:06.635162-127.0.0.1-687
[DEBUG] 2020-12-01 11:44:09,297 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:44:19,848 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "article name": "New ToDo"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 125, in handle
    data = get_request_form_data()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 143, in get_request_form_data
    data = json.loads(frappe.safe_decode(frappe.local.request.get_data()))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] 2020-12-01 11:44:19,852 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:44:19.848842-127.0.0.1-88d
[ERROR] 2020-12-01 11:44:31,932 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "Article Name": "New ToDo"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 125, in handle
    data = get_request_form_data()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 143, in get_request_form_data
    data = json.loads(frappe.safe_decode(frappe.local.request.get_data()))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] 2020-12-01 11:44:31,935 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:44:31.932424-127.0.0.1-3f7
[DEBUG] 2020-12-01 11:45:09,409 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:46:09,557 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:47:09,670 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:48:09,833 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:49:09,954 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 11:49:34,302 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "Article Name": "New ToDo"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 125, in handle
    data = get_request_form_data()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 143, in get_request_form_data
    data = json.loads(frappe.safe_decode(frappe.local.request.get_data()))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] 2020-12-01 11:49:34,304 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:49:34.302335-127.0.0.1-872
[ERROR] 2020-12-01 11:50:02,695 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 130, in handle
    "data": frappe.get_doc(data).insert().as_dict()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-12-01 11:50:02,704 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 11:50:02.695623-127.0.0.1-824
[DEBUG] 2020-12-01 11:50:10,106 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:51:10,218 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:52:10,409 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:53:10,536 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 11:54:10,644 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:10:20,689 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 12:12:52,352 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-12-01 12:12:52,493 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 12:12:52.352691-127.0.0.1-63e
[DEBUG] 2020-12-01 12:13:51,302 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:14:51,422 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:15:51,574 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:16:51,695 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:17:51,808 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 12:18:00,032 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-12-01 12:18:00,110 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 12:18:00.032640-127.0.0.1-42b
[DEBUG] 2020-12-01 12:18:58,548 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:19:58,667 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:20:58,829 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:21:58,992 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:22:59,151 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:23:59,276 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:24:59,467 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:25:59,603 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:26:59,740 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:27:59,950 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:29:00,155 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:30:00,285 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:31:00,395 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:32:00,529 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:33:00,678 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:34:00,828 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:35:00,973 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:36:01,132 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:37:01,293 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:38:01,416 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:39:01,567 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:40:01,741 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 12:40:43,597 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_context"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 214, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 1, in <module>
    @frappe.whitelist()
NameError: name 'frappe' is not defined
[ERROR] 2020-12-01 12:40:43,693 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 12:40:43.598096-127.0.0.1-32a
[DEBUG] 2020-12-01 12:41:01,893 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[ERROR] 2020-12-01 12:41:15,517 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_context"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_context() missing 1 required positional argument: 'context'
[ERROR] 2020-12-01 12:41:15,666 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 12:41:15.518029-127.0.0.1-f7d
[ERROR] 2020-12-01 12:41:39,423 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "library_management.custom_api.api_library.get_context"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/custom_api/api_library.py", line 9, in get_context
    get_article = frappe.db.get_list('article')
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 532, in get_list
    return frappe.get_list(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'article')
[ERROR] 2020-12-01 12:41:39,578 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-12-01 12:41:39.423537-127.0.0.1-aac
[DEBUG] 2020-12-01 12:42:02,034 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:43:02,197 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:44:02,349 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:45:02,474 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:46:02,591 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:47:02,738 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:48:02,891 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:49:03,008 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:50:03,126 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-12-01 12:51:03,236 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
