[ERROR] 2020-11-27 00:08:45,689 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"asd\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 00:08:45,771 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 00:08:45.690464-127.0.0.1-f3f
[ERROR] 2020-11-27 00:09:10,094 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.client.save",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"__run_link_triggers\":1,\"article_name\":\"sad\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 197, in save
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 00:09:10,100 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 00:09:10.095290-127.0.0.1-166
[ERROR] 2020-11-27 02:17:32,766 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.client.save",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"__run_link_triggers\":1,\"article_name\":\"sad\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 197, in save
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:17:32,851 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:17:32.766774-127.0.0.1-ad6
[ERROR] 2020-11-27 02:22:43,826 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"sad\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:22:43,907 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:22:43.826454-127.0.0.1-727
[ERROR] 2020-11-27 02:22:49,295 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"sad\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:22:49,302 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:22:49.296128-127.0.0.1-1d8
[ERROR] 2020-11-27 02:23:56,118 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"asd\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:23:56,207 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:23:56.119585-127.0.0.1-2cc
[ERROR] 2020-11-27 02:27:56,955 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.client.save",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 3\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"__run_link_triggers\":1,\"article_name\":\"dsa\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 197, in save
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:27:56,960 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:27:56.955879-127.0.0.1-d7a
[ERROR] 2020-11-27 02:28:00,560 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"dsa\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:28:00,578 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:28:00.562083-127.0.0.1-608
[ERROR] 2020-11-27 02:32:51,834 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.client.save",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"__run_link_triggers\":1,\"article_name\":\"l\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 197, in save
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:32:51,840 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:32:51.834955-127.0.0.1-2a5
[ERROR] 2020-11-27 02:32:59,666 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"hj\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:32:59,673 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:32:59.666828-127.0.0.1-e5f
[ERROR] 2020-11-27 02:33:26,841 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"das\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:33:26,846 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:33:26.841873-127.0.0.1-f95
[ERROR] 2020-11-27 02:34:53,130 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"das\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:34:53,138 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:34:53.130544-127.0.0.1-fa8
[ERROR] 2020-11-27 02:37:31,964 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"das\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:37:31,968 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:37:31.964755-127.0.0.1-0e9
[ERROR] 2020-11-27 02:38:01,884 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"dsa\",\"author\":\"dsad\",\"publisher\":\"asd\",\"route\":\"sdasd\",\"isbn\":\"adsa\",\"image\":\"/files/favicon-16x16.png\",\"description\":\"<div>adsddasd</div>\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 02:38:01,890 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 02:38:01.885052-127.0.0.1-49c
[ERROR] 2020-11-27 08:21:35,312 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.client.save",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"__run_link_triggers\":1,\"article_name\":\"sdad\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 197, in save
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:21:35,506 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:21:35.365241-127.0.0.1-485
[ERROR] 2020-11-27 08:21:41,963 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"sdf\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:21:41,974 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:21:41.965190-127.0.0.1-2a5
[ERROR] 2020-11-27 08:26:59,705 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cached_timestamp": "2020-11-27 02:32:43.839213",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Article",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
    self.load_templates()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 179, in load_templates
    module = load_doctype_module(self.name)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/library_management/doctype/article/article.py", line 11
    condition_field = “show_in_website”,
                                      ^
SyntaxError: invalid character in identifier
[ERROR] 2020-11-27 08:26:59,930 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:26:59.706484-127.0.0.1-a63
[ERROR] 2020-11-27 08:27:04,003 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cached_timestamp": "",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Article",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
    self.load_templates()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 179, in load_templates
    module = load_doctype_module(self.name)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/library_management/doctype/article/article.py", line 11
    condition_field = “show_in_website”,
                                      ^
SyntaxError: invalid character in identifier
[ERROR] 2020-11-27 08:27:04,097 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:27:04.004017-127.0.0.1-1f5
[ERROR] 2020-11-27 08:33:14,659 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"asd\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:33:14,752 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:33:14.660512-127.0.0.1-27f
[ERROR] 2020-11-27 08:33:59,712 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cached_timestamp": "2020-11-27 02:32:43.839213",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Article",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
    self.load_templates()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/meta.py", line 179, in load_templates
    module = load_doctype_module(self.name)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anotherguest/erpnext/projectName/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anotherguest/erpnext/projectName/apps/library_management/library_management/library_management/doctype/article/article.py", line 14
    page_title_field = “program_name”,
                                    ^
SyntaxError: invalid character in identifier
[ERROR] 2020-11-27 08:33:59,930 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:33:59.713727-127.0.0.1-8bd
[ERROR] 2020-11-27 08:34:53,266 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"asd\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:34:53,346 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:34:53.266905-127.0.0.1-b1b
[ERROR] 2020-11-27 08:37:16,108 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"ads\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:37:16,259 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:37:16.108849-127.0.0.1-eba
[ERROR] 2020-11-27 08:37:31,282 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "frappe.client.save",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"__run_link_triggers\":1,\"article_name\":\"das\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/client.py", line 197, in save
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:37:31,291 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:37:31.283275-127.0.0.1-7b9
[ERROR] 2020-11-27 08:37:34,228 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Article\",\"name\":\"New Article 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Available\",\"article_name\":\"asd\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 225, in insert
    self.set_new_name()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 393, in set_new_name
    set_new_name(self)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 30, in autoname
    self.name = self.scrubbed_title()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 58, in scrubbed_title
    return self.scrub(self.get(self.get_title_field()))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/website/website_generator.py", line 78, in scrub
    return cleanup_page_name(text).replace('_', '-')
AttributeError: 'NoneType' object has no attribute 'replace'
[ERROR] 2020-11-27 08:37:34,234 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-27 08:37:34.228945-127.0.0.1-cf7
[ERROR] 2020-11-27 08:48:02,230 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py:
Site: library.test
Form Dict: {
 "cmd": "upload_file",
 "docname": "how-experts-figure-what-to-focus-on",
 "doctype": "Article",
 "file_url": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEBASEBIQDxAPDw8QDw8PDw8PEA8PFREWFhURFRUYHSggGBolGxUVITEiJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGi0lHSUtLS0tLS0tLS0tLSsrLS0rLS0tLS0rLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tKy0tLf/AABEIALcBEwMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAADAAECBAUGBwj/xAA9EAACAQMCAwUFBwEGBwAAAAABAgADBBESIQUxQQYTUWFxIjKBkaEHFEJSsdHhMyNicoKiwRYkQ3OSsvD/xAAaAQADAQEBAQAAAAAAAAAAAAABAgQDAAUG/8QAJhEAAgICAgEDBAMAAAAAAAAAAAECEQMSITEEE0FRMmFxkSIjof/aAAwDAQACEQMRAD8A8kQyRgFaFDShMicQ1G4K8jNS24sRMYxIZvjytGM8MZdo6+14rnmZq0qwYThqTzRteIlecrhm+SDJ4/wdbpi0zPsuIhuc1E35ShSskcKIaY2iG0xaZ1goBojaIfTEFhsGoOnQJkqlqRNGwQZ3mjWtgV2mUstMoh4ylGzlzTjaJoXNvgwBSaqVk0sdOitoi0Sxoi0w2JqVwkfRD6YtM6w6gNEXdyxpi0wWHUBoj6ZYSiTyjtbkdINhlBlcCHo1iIxonwjBIHTHi2ma1vxIgc4ccVPjMPEJSXMyliiVQ8ifRq1eIEyu1wIBqW0ruIqgjSWWXuErNmVGkzGImyVEspWDixJYjiECIaIpPMUHIaR5WpkwYOLM8U+gaDq0JKoMIHhEaLCPDBpS1Sa1JpGRlKBfo1yp8p0/COIZwDORRsy1a1yh8pVjyUSZsW35PQV3ixMrhfEgQATNdKgMqUkQODGCxwsIBH0w2Ch6L4mhSutt5naY4ESUUzSGRx6LVwQZSenCiMRCuATlsA0RtEsaYtMazPUr6YtMsrTzyl2z4WzEZG0Dml2NHE5OkZooHHKDKTrK/Dwq+k5yuvtGJDJsaZsHp1ZocGtA3ObT8NXEyuFXIWX7nie0nybOXBdheNY+Sve2SgdJhvTAJl65viZnuczbGmlyTZpwb4IVVkEbEIRI6ZqT3zZM14B2kysE7ATuEFylIbEWJWrXQEqPxGK5oeOJs0XYCVnuRmZta+JkKSk7mZSym+PBbNYVhFKgbEaY+qyz0IHnmY4kZIGRFbFJCRzJpCBiijmIQpik6by0jZlTELSaaRkZTVl6hXK8jNK34ww5zIBjgzVTaJpQTOutONg8zNq2uw086Vpp8PvmQjJ2m0cvyYywneYj4lTht2HAmjpmykTODQHTFiG0R+6OM4OPHBx84bBqwIWOFluhZO/uIzDxA2+ch3ZBwRgjoYu66H9KSVtcFjhtvlp11pbKomLwiiOc161fSJFmk5Okep40FGNsr8WI0kTmDZFjNe6rljLFmoxvGhJwiJkgssuTGNgVEqvbnM6C6OdhK3ciaRyv3MpeOukZlHh5POCurPTNlawWZ9/XzGjOTYk8MFH7mVpjNtFVrATPub4TVzSJo4myN3eBZntdFpCsdRg1YCYSyNlkMKXY1cGU2lupVgFokzPY1cfgHT5y+lQAQH3YiDemYrY8U0Ta53ilM0zFAdbOViMlpjESaysjJq0hiPiEATMQkBHJhAEzEGgwZKEVos0qkNmUVOJZpvHUjGcQqtDrWlfE7fsx9mtzcFXr/wDK0TgnV/WZfJPw/wCb5GNKaS5BDHKX0lLsmletVFKgjVDsTj3UHizcgJ61Z9nVpoDXbW+NwpIQfHmZesLOhY0RSoIKajmebMfzMeZM5LtV2rWmpGr2sHrI8vlyfEeD0PH8CPclZt1RbL+FfjmVr3tPRpoFJXSvJdsTxO/7T1WJ9s/PpMv7zVrMFBYljhQMlmPgBMKyy7f+lv8ARj6X6R7BxL7SECkU+e/XbEodnu0FOpTL1q1FGao2lXqorBfQnyM8u+4uWZQruynDBFNXSfAkbCSfg1cbmjU/0/vKcMfTltdsk8nIssNFGke98P4ihHsOjj+4yt+ksVrvM+cWpvTOcPSI5Nuv+oToOD9t7qgQKjfeKfVahy4H91+fzzKVkTfJC8Ukqiz2fWDJrXx1nP8AAuO0rpNVJtwBrpts6HzHh5zSM3STJXNxfJeNyJGpcbSiXAlO9vQBznUkGM2yxXugJl3d8JmXN8STiUajkw7A0C3t4TmZbVTmXVtSxknshiLsNo2BotmH+6ZEqe6ZpUrraLI0jXuV1s5aoUgOcYXAMCau8QdUjRNAEQD2YlihU2gbi9ABiWa8GdUtRkxQFTiQyYoLE4OF1xaoOSBmZRQWNqjAxysIo4MnpgxEHnAaJlZGLXHUZhQBxJo8hia/ZngjXd1RoKMh3BqHotIHLk/D6kTrrlg1vg9i+zDstToW6XNZAbmsodSwyaNMjKqueTEbn1x0nV3HEwNWOQ6xXBCLjkAMADwHKcT2i4n3dJ8Hc56/SefPJKTPVxYYxVGf2s7UnJRD6meW8X4mzsckmW+MXbZwTnXvmYFdh0+c0xwo7LPikWOGWZr1QuQo5u7AkKucZwN2OSAFG5JAHOepWPY2ilNMozsy57kENVcHkazjYDG+hfZ/x+/OX7FWOhe+IDMGxSUjIaruCxHULkrj1/NO/wD+LaPC6FWpUX7xdXBbu6ZPs6/DVzKDYk9SceGKEiBvkGbQUUw/d0EUbIgChR8On0nNcQ4nbEkCshPL+pSAz6k7TieLcUuLyoaldydTEhRtTUk+6ifTx85pcN7D3dcDu6Jy3uiqwpFvRTuPjiPFN9IEpqP1OjUuEBGQdSnqcMp8tQyM+QMxLzhY50wEb8p9xv2gb7hdzY1StVKlu4JXOzUqnlqHst6TR4ffBhkgZUjvKe+llyNx10E4yOk6/kBSsbg0WFWiTSq0zh0O5Q+B/MhnonDO0qV6Iceyw2qJn3H6j06icJxq3LaqygBhqZlUYBQnJXHl0mZwW9NOsN/YqYVvj7p+f6zTFOmZZ8Vqz0W64uekzqt2W5mVS0YtKWQJlqmpMu0rcSlQr4EarfzN2zeLSXJrM6qJm3V54Sk92TK7VPGdR0sl9BalQmSRoNWkHecBcclpXl6iBMYVIQXZiyGjJGxXr4G0wbysWJxDPXJEgomLZr9Rn90YpeZhFBYdTkdMWmTxHAnJG1kMSxa0Gc4URKk1eB1VViG2zyML4AuQFfhjL7w2PWVlsSZ1PErmmU0jc7GZ1rXUHpOVtBdXRjvYMOYO8nStGHMToK1wuN8QDVlxvOTfwK0vkyqVmS3KeyfZT2fFCi9yw/tK/spnpSU9PU/oJwHZixNzc0qSfjb2j+VBuzfKe7hAiBVGlUARQOQUDEw8idcFHjwXZm8XrYHnPKe2N1khfM9Z6PxpyB8J5F2hr5rN5STGrZe+InOcaqe0o8BMthhsdQfqJpmkalXPQb/KUG2qnPSpv/5SxLiyGck5Uel8HpaBSQf9NFAzyLnG5+Y+U4XtNxI3FzUbJKK3d0gfyKcA+rHLHzYz0FKfMjnkY9ek8tt19pNWcd4obxG4zOi7FkqO97D3tC3OK9Nd+dwKYapTJ6Dro5bD6z1y2pil/aIyEFdnz7OkjnPF7Hherk+B4EZwf2nRWFjUUBDV1LjZdJGPTeegk0q9jxnKLlt2/k6rtJd29Wi9CtorK4b2BlsMR7wb8J5b854pVptb3DIcnu2xv+Omwzg+qkT0atZYz7R+U4TtLTzctvnSqKzHbJwT+hEyzLiyrxpPZpmnVwGVFB06BgsdTMDsST9eXWcjcU9LOv5WYD57Tqbg6e5z7y0UB9cCczxOpmtUPiw/9RJU+S59HV0KupFb8yqfmJImLhVD+xo/9tP0lpreXK2jynGmU+8kCZZa3jdzDQpX3kSplxUjOkFMbgpHMi23OW1SQqpA7DwVdckjR+5jCnEcZMKaLNMx6i+EjTWFImDxSs3jNFErFLJSKH05B2RymY4MjFmcahA0kGgxJCMmI0HFYxaoIGTEdMRomDCoYETp/s/7P/fbxKbf0aY72t5oCMJ8Tt6ZjOSirYqg5OkejfZL2dNGgbqoMVLgYpA81oeP+Y7+gE7qsm0IoAwAAAAAAOQHQSpfVtInl5J7NyZ62OGqUUcz2kfAM8e40f7Rz5z0vtHdH9Z5jxJ8u3WdiRtk6B8NQac+JmLxmlprN4Nhh8Rv9Zt2TeyPIkfWV+NWutNQ95PqvWeo4XhVfk8FZa8l3+DoeG8T10qbE41KAx5kMNjt6zl+OWgWtV0+5UY1KRO2xPLyO/1gOE3unKMfZb/S38zdqW/eUstuoOCy+9TPQ/8A3x5iRrg9KXIuznE9WFP9QdCcavMePpOno3rBssu+OneD9RicFX4cQRoAddt1ySd+eBv8pZo8SrIopJlD1JZ3qHfoG930Az5ypZ2lTIX4qcrizruI8U05NQpSXfBdxrIz+FACW+G3mJhUuH9/WRfbwT39wzhVcU/ZyWUe6WXSqrz9pfEwPDbF1bvaoWlvn7xfagqkH3kokaqrY5bH4S9xDiygd3Z94tNhmtXq4NxeVSN6j89CjJ0qDkZJJJJmOTK5G+PEodFDit1rqu22ATy5eePiTOZILtt71RtvVjgS7fVAMouMn3yPDwl7stYa6nesPZp+75uf2H+0WEdnQ0paxbOspIFVVHJVAHwGJIx5EtPQPNIMIFxDMYB4yFkgTGRjtI5hEItIEx2MhmAIiYgZBjGBgCg4MRaDBjFojNUT1RQOYoA2cxHixHAkhYISQjASQjIVik1MYCPiMhGSBnrn2KW+KVzVxu9VKYPki5x83nkaz3X7LrbRw638arVah9C5APyAmHlSrHX3KPEV5L+x17Vd5l8UuNpauHGWmHd5aebsz1lFdnMdon2OPOecXDbn1noHaCoArTz26O5MpxIwysLYnY/4jLeqULFxuOuc48peWezgdwR855Uaysw+J8NK5dBlObKPw/xI2XFGVTTJZqbYJUMQduRxybE6amwmVf8ACUYkodDeAHsn4dJjkwc3Epw+Ukqn+yr3oO9N9+qnY+uDDUatTpVqgeAquB9DMu5sXTdgCPEEH+ZXY+GfmZM01wy2LUlaN1yi+07DV4s2pj/vKdxxDpTBA/OefwEz0XwEOtux57RbQ1Ms8L4e1ZsLsoPt1DyH7tO1t7daaKiDCqNv3PnOR4fdPRPskgdV6fKdEl+GUHl5ecqwOPt2S+VGS5fRdLQbVYFbkeMi1VfESgisI1eAqVI4K+MaoRChZA9cfVBlotUYRMdmkC0hUMFAGwjGQ1xZkDFGDB4+YISRBiseLZLMUEcxQDGJoi0SwFi0SHYtor6ZIJDpTzDijDsBlMLFpMvClJd1GUhGZ4Qz6I7KUe6s7VPyW1LPqVyfqZ4Zb0NTKv5iFHqTgT3+1p6VAHIKF8thjb5STy5dIt8KN7Msuvs77533mHxSqFU+U2bh8L/M5bi+SDvJPc9CJw3aS7JyBynJlp03GVxnM5ljvK8XRPl7A1AQcjYjeX7W5Dbcm6jx9JVMGUA3GQRywesrxZHBkOfAsq+5soDBXtcLsN3+i+sq07qqeoA8QN4RKONzz6zefkcfxJcPg/yuYXgXZ6peVggO+CWduSqJDtD2da0qaH0nO6su4InZ9kblKFCpU/G5K55eyJyXaXiRrVtR3AyMTznNuZ7GkYwMXGJNAW2UbmWLKxao2w9nmT0E37a0VMAD443M2x4nPn2JMudQ49zDThbdcD4y3TsiBgb+c3jSGIPYSrHjjB2iLNlnkVPoxTbNEaBl+vcCCasDN9iXVFEbGHXlIMDmEZto1iUCZo2uOq5idZ1gUSBeLVIESLCCxqCaohAGQzFbHSLymSZ5UpNLJ3is0iDNWKMUigGK1OlDCjGWTOZ59orJpbyXdiMrGRyYdkdqFFMSL04wqSSvmGwUafZSz7y8t1PLvFY+inUf0ntibD45nl/2dWuq6142SmxHqSF/eeokdPDEi8h3I9HxlUPyVL+pgeI/Wcvf3PPn6Tb4xUwNuvScZxC9wT08t5kipLgwuL3A1HI5TnLmqCdpp8bqAnI3mETLMfRLlfJLMmg8eUCDCo02RhRbD4Et0rB3TXsq+LHEymeEq3rMoUnCgYAHKB2OqLdW+Kp3anO536fCNw/hpqHLZCdT1PpFwyy1HU3uj6nwnQ0nA8BiGEF2zDNma4Qe3oqqhQMACCqgSfeiBc5lCkkRNNkC5giuYTuvOOKR8YdgalZ7UGD+6S21MwbDEO4uiGFntA1LYQ/ewZQmcpnOCAlMQLJmWWomQaiY24uoDuxIFIU0zJCnBuHRFV6cCUl9kiSjDudoURTiIl+pRgDRnbHalfEUIaJjwbjalwWeDvFUozfqWuRtKFeyO+J5rTLXEyVXeRqr4Qtag4gwDncQpOxG2QWhJrShmrBRv/PkJsdnuFG4Zg7rSNJQ77F/aZsU6SqN2c78vCaIZKzqfs9ttFN3IwXYKD4gDp47mdkH6nbxmZ2cdHt6RRdI06So/MCQT88y7VXBxgkEH1GMzzpSuTZ60YpRSMni1Xny8zOG4nq1HwO/8TubzntnG/ymDeWeW+HhDFjtHF3tuSNx8Os516ZycA856LeW64x1mTcWiJueePhKITownjs44IfCTBxNO/uAMgDEyGbM3TsnkqLdS6BGAqjzxvJWNoajbcup8BK1GnkiddY22hAOR5t6xkrMsk9UCWhgADkJLujLirHqYj0iS2VadDMKaGJNHkzUgYUBxjpGBzJVHg0zDYKCFIBkzCsTJBTOTo5oALaEWniRqORHpVc84UwUDqGIQz0wYxUCdscolcpIlYQxaZ2x2oEJFplgARtMGwdQemQ7sQjCRJnbB1I6RFFpinbMNHQUpZWmDzEeKKUg6tmp6TH4qq08gAEgajnkq77+fIxooaFYLs9wh7irkD3WxnIyCegz1579Ok1+13BEoNRp02ZO+C020Eo1N2OCufxKRn6jrFFNpwXpWZY5v1lH2O+4TYChQpKpLBEwxPNmzu0Ne3AxnnsMbdDyjxTxGeyjFuK43BG5zkfGZF5cjTtuDtuPnHihiOzDeprOf4xMfi94Fz1PjvFFKILkxm6RzNetqOZFViilJIzW4bR04Y9OXrNqlXiijRJcrthi2YmUmKKFmaA6TCCKKccOBD0lEUUDGRNgI4MUU45gKoBlcpgxRQoDDA7QL5iiisZACN4mzHinHAt4u+IiinHBO9zErRRQHBQRFFFOCf/Z",
 "folder": "Home",
 "is_private": "NaN"
}
Request Error
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 207, in upload_file
    ret.save(ignore_permissions=ignore_permissions)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 896, in run_before_save_methods
    self.run_method("validate")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/core/doctype/file/file.py", line 94, in validate
    self.validate_duplicate_entry()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/core/doctype/file/file.py", line 188, in validate_duplicate_entry
    self.generate_content_hash()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/core/doctype/file/file.py", line 219, in generate_content_hash
    with open(get_files_path(file_name, is_private=self.is_private), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './library.test/public/files/Z'
[ERROR] 2020-11-27 08:48:02,322 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/handler.py", line 207, in upload_file
    ret.save(ignore_permissions=ignore_permissions)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 896, in run_before_save_methods
    self.run_method("validate")
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/core/doctype/file/file.py", line 94, in validate
    self.validate_duplicate_entry()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/core/doctype/file/file.py", line 188, in validate_duplicate_entry
    self.generate_content_hash()
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/core/doctype/file/file.py", line 219, in generate_content_hash
    with open(get_files_path(file_name, is_private=self.is_private), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './library.test/public/files/Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[DEBUG] 2020-11-27 09:03:25,099 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:03:25,310 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:04:25,447 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:04:25,510 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:05:25,644 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:05:25,711 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:06:25,870 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:06:25,929 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:07:26,064 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:07:26,137 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:08:26,279 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:08:26,341 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:09:26,486 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:09:26,535 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:10:26,686 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:10:26,729 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:11:26,848 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:11:26,921 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:12:27,095 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:12:27,155 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:13:27,285 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:13:27,343 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:14:27,464 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:14:27,514 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:15:27,617 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:15:27,658 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:16:27,779 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:16:27,862 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:17:28,004 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:17:28,047 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:18:28,180 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:18:28,230 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:19:28,408 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:19:28,492 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:20:28,654 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:20:28,714 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:21:28,865 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
[DEBUG] 2020-11-27 09:21:28,934 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: testsite
Queued events for site testsite
[DEBUG] 2020-11-27 09:22:29,059 | /home/anotherguest/erpnext/projectName/apps/frappe/frappe/utils/scheduler.py:
Site: library.test
Queued events for site library.test
